const SAVE_SHOPIFY_DATA = 'SAVE_SHOPIFY_DATA'
const SHOP_EXISTS       = 'SHOP_EXISTS'
const SHOP_NOT_EXISTS   = 'SHOP_NOT_EXISTS'

const SHOP_IS_LOADING       =   'SHOP_IS_LOADING'
const SHOP_IS_NOT_LOADING   =   'SHOP_IS_NOT_LOADING'
const SET_ERROR             =   'SET_ERROR'
const CLEAR_ERROR           =   'CLEAR_ERROR'

const UPDATE_PRUEBA_TITULO          =   'UPDATE_PRUEBA_TITULO'
const UPDATE_PRUEBA_NIETO           =   'UPDATE_PRUEBA_NIETO'


export default {
    SAVE_SHOPIFY_DATA,
    SHOP_EXISTS,
    SHOP_NOT_EXISTS,
    SHOP_IS_LOADING,
    SHOP_IS_NOT_LOADING,
    SET_ERROR,
    CLEAR_ERROR,

    UPDATE_PRUEBA_TITULO,
    UPDATE_PRUEBA_NIETO
}